/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peterdonniel;

import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Peter
 */
public class perualila extends javax.swing.JFrame {

    /**
     * Creates new form perualila
     */
    public perualila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenuMeals = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfButteredChicken = new javax.swing.JTextField();
        tfPorkLechon = new javax.swing.JTextField();
        tfPorkSizzling = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlTotal = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfTotalCosts = new javax.swing.JTextField();
        tfCostDrinks = new javax.swing.JTextField();
        tfCostMeal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTextAreaReceipt = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnTotal = new javax.swing.JButton();
        btnReciept = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnlTax = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        tfSubTotal = new javax.swing.JTextField();
        tfTax = new javax.swing.JTextField();
        pnlMenuDrinks = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfCokeFloat = new javax.swing.JTextField();
        tfRoyal = new javax.swing.JTextField();
        tfMtDew = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1080, 1920));
        setPreferredSize(new java.awt.Dimension(1080, 1920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 5, true));
        jPanel1.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("VILLANUEVA RESTAURANT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1500, 140));

        pnlMenuMeals.setBackground(new java.awt.Color(51, 153, 255));
        pnlMenuMeals.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 5, true));
        pnlMenuMeals.setPreferredSize(new java.awt.Dimension(400, 190));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("MEALS");

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel19.setText("PORK SIZZLING");

        tfButteredChicken.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfButteredChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfButteredChickenActionPerformed(evt);
            }
        });

        tfPorkLechon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfPorkLechon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPorkLechonActionPerformed(evt);
            }
        });

        tfPorkSizzling.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfPorkSizzling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPorkSizzlingActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel20.setText("PORK LECHON");

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel21.setText("CHICKEN FRY");

        javax.swing.GroupLayout pnlMenuMealsLayout = new javax.swing.GroupLayout(pnlMenuMeals);
        pnlMenuMeals.setLayout(pnlMenuMealsLayout);
        pnlMenuMealsLayout.setHorizontalGroup(
            pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuMealsLayout.createSequentialGroup()
                .addGroup(pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuMealsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPorkSizzling, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPorkLechon, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfButteredChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMenuMealsLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlMenuMealsLayout.setVerticalGroup(
            pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuMealsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfButteredChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPorkSizzling, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPorkLechon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(12, 12, 12))
        );

        getContentPane().add(pnlMenuMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 380, -1));

        pnlTotal.setBackground(new java.awt.Color(51, 153, 255));
        pnlTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 5, true));
        pnlTotal.setPreferredSize(new java.awt.Dimension(400, 190));

        jLabel31.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel31.setText("COST OF MEALS");

        jLabel32.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel32.setText("COST OF DRINKS");

        jLabel33.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel33.setText("TOTAL COST");

        tfTotalCosts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfTotalCosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalCostsActionPerformed(evt);
            }
        });

        tfCostDrinks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfCostDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCostDrinksActionPerformed(evt);
            }
        });

        tfCostMeal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfCostMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCostMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCostDrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotalCosts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCostMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tfCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tfTotalCosts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(pnlTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 380, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 5, true));

        taTextAreaReceipt.setColumns(20);
        taTextAreaReceipt.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        taTextAreaReceipt.setRows(5);
        jScrollPane1.setViewportView(taTextAreaReceipt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 690, 580));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 5, true));

        btnTotal.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        btnTotal.setText("TOTAL");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnReciept.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        btnReciept.setText("RECEIPT");
        btnReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecieptActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReciept, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReciept, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 790, 150));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, -1));

        pnlTax.setBackground(new java.awt.Color(51, 153, 255));
        pnlTax.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 5, true));
        pnlTax.setToolTipText("");
        pnlTax.setPreferredSize(new java.awt.Dimension(400, 190));

        jLabel38.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel38.setText("TAX :");

        jLabel39.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel39.setText("SUB TOTAL :");

        jLabel40.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel40.setText("TOTAL :");

        tfTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        tfSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubTotalActionPerformed(evt);
            }
        });

        tfTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaxLayout = new javax.swing.GroupLayout(pnlTax);
        pnlTax.setLayout(pnlTaxLayout);
        pnlTaxLayout.setHorizontalGroup(
            pnlTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaxLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pnlTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        pnlTaxLayout.setVerticalGroup(
            pnlTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaxLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnlTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(28, 28, 28))
        );

        getContentPane().add(pnlTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 380, -1));

        pnlMenuDrinks.setBackground(new java.awt.Color(51, 153, 255));
        pnlMenuDrinks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 5, true));
        pnlMenuDrinks.setPreferredSize(new java.awt.Dimension(400, 190));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("DRINKS");

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel23.setText("MT. DEW");

        tfCokeFloat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfCokeFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCokeFloatActionPerformed(evt);
            }
        });

        tfRoyal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfRoyal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRoyalActionPerformed(evt);
            }
        });

        tfMtDew.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfMtDew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMtDewActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel24.setText("ROYAL");

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel25.setText("COKE FLOAT");

        javax.swing.GroupLayout pnlMenuDrinksLayout = new javax.swing.GroupLayout(pnlMenuDrinks);
        pnlMenuDrinks.setLayout(pnlMenuDrinksLayout);
        pnlMenuDrinksLayout.setHorizontalGroup(
            pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDrinksLayout.createSequentialGroup()
                .addGroup(pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuDrinksLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuDrinksLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRoyal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMtDew, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCokeFloat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlMenuDrinksLayout.setVerticalGroup(
            pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDrinksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCokeFloat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMtDew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRoyal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(12, 12, 12))
        );

        getContentPane().add(pnlMenuDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 380, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        SubClass ItemCost = new SubClass();
        double nTax, nSubtotal, nTotal;

        double qButteredChicken = ItemCost.isEmpty(tfButteredChicken) ? 0.0 : Double.parseDouble(tfButteredChicken.getText());
        double qPorkSizzling = ItemCost.isEmpty(tfPorkSizzling) ? 0.0 : Double.parseDouble(tfPorkSizzling.getText());
        double qPorkLechon = ItemCost.isEmpty(tfPorkLechon) ? 0.0 : Double.parseDouble(tfPorkLechon.getText());
        double qCokeFloat = ItemCost.isEmpty(tfCokeFloat) ? 0.0 : Double.parseDouble(tfCokeFloat.getText());
        double qMtDew = ItemCost.isEmpty(tfMtDew) ? 0.0 : Double.parseDouble(tfMtDew.getText());
        double qRoyal = ItemCost.isEmpty(tfRoyal) ? 0.0 : Double.parseDouble(tfRoyal.getText());

        ItemCost.ButteredChicken = ItemCost.PButteredChicken * qButteredChicken;
        ItemCost.PorkSizzling = ItemCost.PPorkSizzling * qPorkSizzling;
        ItemCost.PorkLechon = ItemCost.PPorkLechon * qPorkLechon;
        ItemCost.CokeFloat = ItemCost.PCokeFloat * qCokeFloat;
        ItemCost.MtDew = ItemCost.PMtDew * qMtDew;
        ItemCost.Royal = ItemCost.PRoyal * qRoyal;
        nSubtotal = ItemCost.GetAmount();
        nTax = ItemCost.fFindTax(nSubtotal);
        nTotal = nSubtotal + nTax;
        String SubTotal = String.format("₱%.2f", nSubtotal);
        tfSubTotal.setText(SubTotal);
        String Tax = String.format("₱%.2f", nTax);
        tfTax.setText(Tax);
        String Total = String.format("₱%.2f", nTotal);
        tfTotal.setText(Total);
        String M1 = String.format("₱%.2f", ItemCost.MealTotal);
        tfCostMeal.setText(M1);
        String M2 = String.format("₱%.2f", ItemCost.DrinkTotal);
        tfCostDrinks.setText(M2);
        String CostofItems = String.format("₱%.2f", ItemCost.MealDrinkTotal);
        tfTotalCosts.setText(CostofItems);

    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecieptActionPerformed
        // TODO add your handling code here:
        int refs = 69420 + (int) (Math.random() * 911620);
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        taTextAreaReceipt.append("""
                                 \t         Villanueva Restaurant
                                 
                                    Reference:\t\t\t#""" + refs
                + "\n======================================================\n\n"
                + "   Meals:\t\t\t" + tfCostMeal.getText() + "\n\n"
                + "   Drinks:\t\t\t" + tfCostDrinks.getText() + "\n\n"
                + "   Total Meals & Drinks:\t\t" + tfTotalCosts.getText() + "\n\n"
                + "======================================================" + "\n\n"
                + "   Tax:\t\t\t\t" + tfTax.getText() + "\n\n"
                + "   SubTotal:\t\t\t" + tfSubTotal.getText() + "\n\n"
                + "   Total:\t\t\t" + tfTotal.getText() + "\n\n"
                + "======================================================"
                + "\n   Date: " + Tdate.format(timer.getTime())
                + "\t\tTime: " + tTime.format(timer.getTime())
                + "\n\n\t        Thank you! Come Again.");


    }//GEN-LAST:event_btnRecieptActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        JTextField cleartext = null;
        for (Component c : pnlMenuMeals.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }
        for (Component c : pnlMenuDrinks.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }
        for (Component c : pnlTotal.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }
        for (Component c : pnlTax.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }
        taTextAreaReceipt.setText(null);


    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        SubClass iExit = new SubClass();
        iExit.iExitSystem();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfButteredChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfButteredChickenActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfButteredChickenActionPerformed

    private void tfPorkLechonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPorkLechonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPorkLechonActionPerformed

    private void tfPorkSizzlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPorkSizzlingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPorkSizzlingActionPerformed

    private void tfCokeFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCokeFloatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCokeFloatActionPerformed

    private void tfRoyalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRoyalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRoyalActionPerformed

    private void tfMtDewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMtDewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMtDewActionPerformed

    private void tfTotalCostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalCostsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalCostsActionPerformed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    private void tfCostDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCostDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCostDrinksActionPerformed

    private void tfCostMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCostMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCostMealActionPerformed

    private void tfSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSubTotalActionPerformed

    private void tfTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perualila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new perualila().setVisible(true);
        }
        }); */
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perualila().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReciept;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlMenuDrinks;
    private javax.swing.JPanel pnlMenuMeals;
    private javax.swing.JPanel pnlTax;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JTextArea taTextAreaReceipt;
    private javax.swing.JTextField tfButteredChicken;
    private javax.swing.JTextField tfCokeFloat;
    private javax.swing.JTextField tfCostDrinks;
    private javax.swing.JTextField tfCostMeal;
    private javax.swing.JTextField tfMtDew;
    private javax.swing.JTextField tfPorkLechon;
    private javax.swing.JTextField tfPorkSizzling;
    private javax.swing.JTextField tfRoyal;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTax;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalCosts;
    // End of variables declaration//GEN-END:variables
}
